[package]
name = "mp3t"
version = "0.1.0"
authors = ["Kasun Vithanage <alankasun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
pad = "0.1.6"
colored = "1.9.3"
dialoguer = "0.6.2"
